### ISSUE TITLE
Basic indentation

### ISSUE THREAD

**Issue by aivano** [larics/coding_standard#1]
As stated [here](https://github.com/larics/coding_standard/blob/master/CppCodingStyleGuidelines.md#LayoutAndCommentsLayout) basic indentation should be 2 in C++. 
My suggestion is to let user decide between indentation of 2 or 4 and be consistent within the file. Indentation of 4 works fine for smaller files without a lot of nesting. @dmiklic

**Comment by dmiklic** [comment]
I think we should stick to 2 spaces. The only valid reason for breaking this rule is if you are editing a file that is already indented with 4 spaces.
